/**
 * @file ciot_default_config.h
 * @author your name (you@domain.com)
 * @brief
 * @version 0.1
 * @date 2023-06-19
 *
 * @copyright Copyright (c) 2023
 *
 */

#ifndef __CIOT_DEFAULT_CONFIG__H__
#define __CIOT_DEFAULT_CONFIG__H__

#include "ciot_system.h"

#define CIOT_CONFIG_DEVICE_TYPE CIOT_SYSTEM_DEVICE_TYPE_GENERIC
#define CIOT_CONFIG_OS CIOT_SYSTEM_OS_FREERTOS
#define CIOT_CONFIG_BOARD "ESP32 Devkit"
#define CIOT_CONFIG_MCU "ESP32"

#define CIOT_CONFIG_API_ERROR_MESSAGES 0
#define CIOT_CONFIG_CONSOLE_ERROR_MESSAGES 0

/**
 *  Hardware Features
 */
#define CIOT_CONFIG_FEATURE_SPI 1
#define CIOT_CONFIG_FEATURE_UART 1
#define CIOT_CONFIG_FEATURE_USB 0
#define CIOT_CONFIG_FEATURE_ETHERNET 0
#define CIOT_CONFIG_FEATURE_WIFI 1
#define CIOT_CONFIG_FEATURE_BLE 1
#define CIOT_CONFIG_FEATURE_ZIGBEE 0
#define CIOT_CONFIG_FEATURE_LORA 0
#define CIOT_CONFIG_FEATURE_RS232 0
#define CIOT_CONFIG_FEATURE_RS485 0
#define CIOT_CONFIG_FEATURE_CAN 0
#define CIOT_CONFIG_FEATURE_EEPROM 0
#define CIOT_CONFIG_FEATURE_FLASH 1
#define CIOT_CONFIG_FEATURE_SDCARD 0
#define CIOT_CONFIG_FEATURE_HARDDISK 0
#define CIOT_CONFIG_FEATURE_DISPLAY 0

/**
 *  Software Features
 */
#define CIOT_CONFIG_FEATURE_NTP 1

#define CIOT_CONFIG_FEATURES                                             \
    (CIOT_CONFIG_FEATURE_I2C << CIOT_SYSTEM_FEATURE_I2C) |               \
        (CIOT_CONFIG_FEATURE_SPI << CIOT_SYSTEM_FEATURE_SPI) |           \
        (CIOT_CONFIG_FEATURE_UART << CIOT_SYSTEM_FEATURE_UART) |         \
        (CIOT_CONFIG_FEATURE_USB << CIOT_SYSTEM_FEATURE_USB) |           \
        (CIOT_CONFIG_FEATURE_ETHERNET << CIOT_SYSTEM_FEATURE_ETHERNET) | \
        (CIOT_CONFIG_FEATURE_WIFI << CIOT_SYSTEM_FEATURE_WIFI) |         \
        (CIOT_CONFIG_FEATURE_BLE << CIOT_SYSTEM_FEATURE_BLE) |           \
        (CIOT_CONFIG_FEATURE_ZIGBEE << CIOT_SYSTEM_FEATURE_ZIGBEE) |     \
        (CIOT_CONFIG_FEATURE_LORA << CIOT_SYSTEM_FEATURE_LORA) |         \
        (CIOT_CONFIG_FEATURE_RS232 << CIOT_SYSTEM_FEATURE_RS232) |       \
        (CIOT_CONFIG_FEATURE_RS485 << CIOT_SYSTEM_FEATURE_RS485) |       \
        (CIOT_CONFIG_FEATURE_CAN << CIOT_SYSTEM_FEATURE_CAN) |           \
        (CIOT_CONFIG_FEATURE_EEPROM << CIOT_SYSTEM_FEATURE_EEPROM) |     \
        (CIOT_CONFIG_FEATURE_FLASH << CIOT_SYSTEM_FEATURE_FLASH) |       \
        (CIOT_CONFIG_FEATURE_SDCARD << CIOT_SYSTEM_FEATURE_SDCARD) |     \
        (CIOT_CONFIG_FEATURE_HARDDISK << CIOT_SYSTEM_FEATURE_HARDDISK) | \
        (CIOT_CONFIG_FEATURE_DISPLAY << CIOT_SYSTEM_FEATURE_DISPLAY) |   \
        (CIOT_CONFIG_FEATURE_NTP << CIOT_SYSTEM_FEATURE_NTP)

#endif //!__CIOT_DEFAULT_CONFIG__H__